name: Pylint

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Verify SSH connection
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "SSH connection successful"'

      - name: Run Streamlit App on EC2
        run: |
            git pull https://${{ secrets.GH_TOKEN }}@github.com/Christopher-Yammine/recipe-finder.git main
            # Install dependencies
            pip install -r requirements.txt
            # Kill any existing Streamlit processes
            pkill -f streamlit || true
            echo "streamlit instance killed"
            # Run the Streamlit app in the background
            echo "running streamlit app"
            streamlit run app.py 


